import * as pdfjsLib from 'https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.worker.min.mjs';
const $=id=>document.getElementById(id),E={pdfInput:$('pdfInput'),exportMd:$('exportMd'),status:$('status'),pageInput:$('pageInput'),total:$('total'),prev:$('prev'),next:$('next'),title:$('title'),thumbPrev:$('thumbPrev'),thumbNext:$('thumbNext'),thumbRail:$('thumbRail'),pLabel:$('pLabel'),chars:$('chars'),editor:$('editor'),time:$('time'),filename:$('filename'),toast:$('toast')};
const DB='lecture-helper-v5',PS='projects',NS='notes',LAST='lh-v5-last';let db,pdfDoc=null,project=null,currentPage=1,saveTimer=null,thumbGen=0;
function toast(t){E.toast.textContent=t;E.toast.classList.add('show');setTimeout(()=>E.toast.classList.remove('show'),1300)}function safe(n){return(n||'lecture').replace(/[\\/:*?"<>|]/g,'_').trim()||'lecture'}function now(){return new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())}function clamp(n,a,b){return Math.max(a,Math.min(b,n))}function req(r){return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}function done(tx){return new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error)})}
async function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(PS))d.createObjectStore(PS,{keyPath:'id'});if(!d.objectStoreNames.contains(NS)){const s=d.createObjectStore(NS,{keyPath:'key'});s.createIndex('projectId','projectId')}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function put(s,o){const tx=db.transaction(s,'readwrite');tx.objectStore(s).put(o);await done(tx)}async function get(s,k){const tx=db.transaction(s);const x=await req(tx.objectStore(s).get(k));await done(tx);return x}async function getByProject(s,id){const tx=db.transaction(s);const x=await req(tx.objectStore(s).index('projectId').getAll(IDBKeyRange.only(id)));await done(tx);return x.sort((a,b)=>a.page-b.page)}function key(p){return`${project.id}:${p}`}
async function saveProject(){if(!project)return;project.title=E.title.value||project.title;project.page=currentPage;project.updated=Date.now();await put(PS,project);localStorage.setItem(LAST,project.id)}async function saveNote(){if(!project)return;await put(NS,{key:key(currentPage),projectId:project.id,page:currentPage,text:E.editor.value,updated:Date.now()});E.chars.textContent=`${E.editor.value.length}자`}function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{await Promise.all([saveProject(),saveNote()]);E.status.textContent=`저장됨 · ${now()}`},220)}
async function loadPdf(file){try{const buf=await file.arrayBuffer();pdfDoc=await pdfjsLib.getDocument({data:buf.slice(0)}).promise;project={id:`${file.name}:${file.size}:${file.lastModified}`,title:file.name.replace(/\.pdf$/i,''),filename:file.name,pdfBlob:new Blob([buf],{type:'application/pdf'}),page:1,total:pdfDoc.numPages,updated:Date.now()};currentPage=1;await put(PS,project);localStorage.setItem(LAST,project.id);E.title.value=project.title;E.filename.textContent=file.name;E.total.textContent=pdfDoc.numPages;await render();toast('PDF 열림')}catch(e){console.error(e);toast('PDF를 열지 못했습니다')}}async function restore(){try{const id=localStorage.getItem(LAST);if(!id)return;const p=await get(PS,id);if(!p?.pdfBlob)return;project=p;pdfDoc=await pdfjsLib.getDocument({data:await p.pdfBlob.arrayBuffer()}).promise;currentPage=clamp(p.page||1,1,pdfDoc.numPages);E.title.value=p.title||'';E.filename.textContent=p.filename||'';E.total.textContent=pdfDoc.numPages;await render()}catch(e){console.warn(e)}}
async function render(){if(!pdfDoc)return;currentPage=clamp(currentPage,1,pdfDoc.numPages);E.pageInput.value=currentPage;E.pLabel.textContent=currentPage;const n=await get(NS,key(currentPage));E.editor.value=n?.text||'';E.chars.textContent=`${E.editor.value.length}자`;E.status.textContent=`${currentPage}/${pdfDoc.numPages}`;await renderThumbs()}
async function renderThumbs(){const gen=++thumbGen;E.thumbRail.innerHTML='';const radius=4,start=Math.max(1,Math.min(currentPage-radius,Math.max(1,pdfDoc.numPages-radius*2))),end=Math.min(pdfDoc.numPages,start+radius*2);for(let p=start;p<=end;p++){if(gen!==thumbGen)return;const b=document.createElement('button');b.className='thumb'+(p===currentPage?' active':'');b.type='button';const lab=document.createElement('span');lab.textContent=`${p}p.`;b.appendChild(lab);const pg=await pdfDoc.getPage(p),vp=pg.getViewport({scale:.22}),c=document.createElement('canvas'),dpr=Math.min(devicePixelRatio||1,1.5);c.width=Math.round(vp.width*dpr);c.height=Math.round(vp.height*dpr);const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);await pg.render({canvasContext:ctx,viewport:vp}).promise;const img=document.createElement('img');img.src=c.toDataURL('image/jpeg',.72);b.appendChild(img);b.onclick=()=>go(p);E.thumbRail.appendChild(b)}requestAnimationFrame(()=>E.thumbRail.querySelector('.active')?.scrollIntoView({inline:'center',block:'nearest',behavior:'smooth'}))}
async function go(p){if(!pdfDoc)return;await saveNote();currentPage=clamp(Number(p)||1,1,pdfDoc.numPages);await saveProject();await render()}
function insert(text){const s=E.editor.selectionStart,e=E.editor.selectionEnd;E.editor.setRangeText(text,s,e,'end');E.editor.focus();scheduleSave()}
function download(text,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
E.pdfInput.onchange=e=>{const f=e.target.files?.[0];if(f)loadPdf(f);e.target.value=''};E.prev.onclick=()=>go(currentPage-1);E.next.onclick=()=>go(currentPage+1);E.thumbPrev.onclick=()=>go(currentPage-1);E.thumbNext.onclick=()=>go(currentPage+1);E.pageInput.onchange=()=>go(E.pageInput.value);E.editor.addEventListener('input',scheduleSave);E.title.addEventListener('input',scheduleSave);document.querySelectorAll('[data-tag]').forEach(b=>b.onclick=()=>insert(b.dataset.tag));E.time.onclick=()=>insert(`[${now()}] `);E.exportMd.onclick=async()=>{if(!project||!pdfDoc)return;await Promise.all([saveProject(),saveNote()]);const notes=await getByProject(NS,project.id);let out=`# ${E.title.value||project.title}\n\n`;for(let p=1;p<=pdfDoc.numPages;p++){const n=notes.find(x=>x.page===p);out+=`<<<PAGE ${p}>>>\n\n### 수업필기\n${n?.text||''}\n\n`}download(out,`${safe(E.title.value)}_V5_notes.md`);toast('MD 저장 완료')};window.addEventListener('keydown',e=>{if(e.target===E.editor||e.target===E.title||e.target===E.pageInput)return;if(e.key==='ArrowLeft')go(currentPage-1);if(e.key==='ArrowRight')go(currentPage+1)});db=await openDb();await restore();