from pathlib import Path
import re

def one(s,p,r,n,flags=0):
    x,c=re.subn(p,r,s,1,flags=flags)
    if c!=1: raise SystemExit(f'{n}:{c}')
    return x

# HTML
p=Path('v4/index.html');s=p.read_text()
s=one(s,r'<div class="titleline">.*?</div>','<div class="titleline"><input id="title" class="title" placeholder="강의 제목"><span id="inputBadge" class="badge">✏️ Pencil · 👆 손가락 이동</span><label class="viewselect">동시보기 <select id="viewCount" class="tool"><option value="1">1쪽</option><option value="2">2쪽</option><option value="3">3쪽</option><option value="4">4쪽</option></select></label><button id="layoutToggle" class="tool layout-toggle">코멘트 ↓</button></div>','title')
s=one(s,r'<aside class="notes">.*?</aside>','''<aside class="notes"><div class="nhead"><div><small style="color:#6b7280;font-weight:800">PAGE NOTE</small><h2><span id="pLabel">1</span>p.</h2></div></div><div class="tags"><button class="tag exam" data-tag="[시험] ">시험</button><button class="tag important" data-tag="[중요] ">중요</button><button class="tag prof" data-tag="[교수설명] ">교수설명</button><button class="tag question" data-tag="[질문] ">질문</button><button id="time" class="tag">시간</button></div><textarea id="editor" class="editor" placeholder="이 페이지에 대한 코멘트를 입력하세요."></textarea><div class="meta"><span id="chars">0자</span><span>코멘트·필기 자동저장</span></div><section class="transcriptbox"><div class="transcripthead"><div><b>🎙 실시간 전사</b><small>코멘트와 별도로 저장됨</small></div><button id="mic" class="btn micbtn">🎤 시작</button></div><textarea id="transcript" class="transcript" placeholder="음성 전사 내용이 이곳에 별도로 쌓입니다."></textarea><div class="meta"><span id="transcriptChars">0자</span><span>페이지별 자동저장</span></div></section><div class="pinsbox"><b>📌 이 페이지 코멘트 핀</b><div id="pinList" class="pinlist"></div></div><div class="exports"><button id="docx">Word<br><small>A4 4쪽 배치</small></button><button id="printBtn">PDF<br><small>A4 4쪽 배치</small></button><button id="md">Markdown<br><small>코멘트+전사</small></button><button id="json">JSON<br><small>전체 백업</small></button></div></aside>''','aside',re.S)
s=s.replace('</main>\n<div id="toast"','</main>\n<div id="pinPopover" class="pinpopover hidden"><textarea id="pinText" placeholder="이 위치에 짧은 코멘트"></textarea><div class="pinactions"><button id="pinCancel" class="tool">취소</button><button id="pinSave" class="btn primary">저장</button></div></div>\n<div id="toast"',1)
p.write_text(s)

# CSS
p=Path('v4/styles.css');s=p.read_text()
if 'V4 feature pack' not in s:s+='''\n/* V4 feature pack */\n.viewselect{display:inline-flex;align-items:center;gap:5px;font-size:11px;color:var(--muted)}.transcriptbox{border:1px solid #c7d2fe;border-radius:14px;background:#f8faff;padding:10px;display:grid;gap:8px}.transcripthead{display:flex;align-items:center;justify-content:space-between;gap:8px}.transcripthead>div{display:grid}.transcripthead small{font-size:10px;color:var(--muted)}.micbtn{min-height:34px;font-size:11px}.micbtn.listening{background:#fee2e2}.transcript{width:100%;min-height:140px;max-height:260px;resize:vertical;border:1px solid #dbeafe;border-radius:11px;background:#fff;padding:10px}.pinpopover{position:fixed;z-index:120;width:min(280px,calc(100vw - 24px));padding:10px;background:#fff;border:1px solid #f59e0b;border-radius:14px;box-shadow:0 14px 44px #11182738}.pinpopover textarea{width:100%;height:86px;resize:none;border:1px solid var(--border);border-radius:10px;padding:9px}.pinactions{display:flex;justify-content:flex-end;gap:7px;margin-top:8px}.stageInner.multi{display:grid;grid-template-columns:repeat(var(--grid-cols,2),minmax(0,1fr));gap:12px;align-items:start;justify-items:center;width:100%;min-width:100%}.previewCard{position:relative;width:100%;border:2px solid transparent;border-radius:10px;padding:5px;background:#cfd4dc;display:flex;justify-content:center}.previewCard img{display:block;max-width:100%;object-fit:contain;background:#fff}.previewPageNo{position:absolute;left:8px;top:8px;background:#111827d9;color:#fff;font-size:10px;font-weight:800;padding:3px 7px;border-radius:999px}\n'''
p.write_text(s)

# JS
p=Path('v4/app.js');s=p.read_text()
s=s.replace("mic:$('mic'),pinList", "mic:$('mic'),transcript:$('transcript'),transcriptChars:$('transcriptChars'),pinList",1).replace("inputBadge:$('inputBadge')};","inputBadge:$('inputBadge'),viewCount:$('viewCount'),pinPopover:$('pinPopover'),pinText:$('pinText'),pinSave:$('pinSave'),pinCancel:$('pinCancel')};",1)
s=s.replace("listening=false,lineWidth=2.2;","listening=false,lineWidth=2.2,viewCount=Math.max(1,Math.min(4,Number(localStorage.getItem('lh-v4-view-count'))||1)),pendingPin=null;",1).replace("AS='annotations',LAST","AS='annotations',TS='transcripts',LAST",1).replace("indexedDB.open(DB,1)","indexedDB.open(DB,2)",1)
s=s.replace("if(!d.objectStoreNames.contains(AS)){const s=d.createObjectStore(AS,{keyPath:'key'});s.createIndex('projectId','projectId')}","if(!d.objectStoreNames.contains(AS)){const s=d.createObjectStore(AS,{keyPath:'key'});s.createIndex('projectId','projectId')}if(!d.objectStoreNames.contains(TS)){const s=d.createObjectStore(TS,{keyPath:'key'});s.createIndex('projectId','projectId')}",1)
s=s.replace("async function saveAnnotation()", "async function saveTranscript(){if(!project)return;await put(TS,{key:noteKey(currentPage),projectId:project.id,page:currentPage,text:E.transcript.value,updated:Date.now()});E.transcriptChars.textContent=`${E.transcript.value.length}자`}\nasync function saveAnnotation()",1).replace("saveProject(),saveNote(),saveAnnotation()","saveProject(),saveNote(),saveTranscript(),saveAnnotation()",1)
s=one(s,r'function fitScale\(viewport\)\{.*?\}',"function fitScale(viewport){const cols=viewCount===1?1:2,rows=viewCount<=2?1:2,gap=viewCount===1?0:12;const w=Math.max(180,(E.stage.clientWidth-36-gap*(cols-1))/cols),h=Math.max(180,(E.stage.clientHeight-36-gap*(rows-1))/rows);return Math.min(w/viewport.width,h/viewport.height,2.2)}",'fit')
s=s.replace("const [n,a]=await Promise.all([get(NS,noteKey(currentPage)),get(AS,noteKey(currentPage))]);E.editor.value=n?.text||'';E.chars.textContent=`${E.editor.value.length}자`;pageData=", "const [n,a,t]=await Promise.all([get(NS,noteKey(currentPage)),get(AS,noteKey(currentPage)),get(TS,noteKey(currentPage))]);E.editor.value=n?.text||'';E.chars.textContent=`${E.editor.value.length}자`;E.transcript.value=t?.text||'';E.transcriptChars.textContent=`${E.transcript.value.length}자`;pageData=",1).replace("drawAllStrokes();renderPins();E.status", "drawAllStrokes();renderPins();await renderMultiPreviews();E.status",1)
anchor='function pagePointFromClient'
fn="async function renderMultiPreviews(){E.stageInner.querySelectorAll('.previewCard').forEach(x=>x.remove());E.stageInner.classList.toggle('multi',viewCount>1);E.stageInner.style.setProperty('--grid-cols',viewCount===1?'1':'2');if(viewCount<=1||!pdfDoc)return;for(let i=1;i<viewCount;i++){const p=currentPage+i;if(p>pdfDoc.numPages)break;const b=document.createElement('button');b.className='previewCard';b.type='button';const l=document.createElement('span');l.className='previewPageNo';l.textContent=`${p}p.`;b.appendChild(l);const c=await composePageImage(p,.9),im=document.createElement('img');im.src=c.toDataURL('image/jpeg',.82);b.appendChild(im);b.onclick=()=>goPage(p);E.stageInner.appendChild(b)}}\n"
s=s.replace(anchor,fn+anchor,1)
s=one(s,r'async function addPinAt\(clientX,clientY\)\{.*?\n\}',"function showPinPopover(clientX,clientY){if(!project||tool!=='pin')return;pendingPin=pagePointFromClient(clientX,clientY,1);E.pinText.value='';E.pinPopover.classList.remove('hidden');const w=280,h=150,p=10;E.pinPopover.style.left=`${Math.max(p,Math.min(innerWidth-w-p,clientX+12))}px`;E.pinPopover.style.top=`${Math.max(p,Math.min(innerHeight-h-p,clientY+12))}px`;setTimeout(()=>E.pinText.focus(),20)}\nfunction hidePinPopover(){pendingPin=null;E.pinPopover.classList.add('hidden');E.pinText.value=''}\nasync function commitPin(){const text=E.pinText.value.trim();if(!pendingPin||!text)return hidePinPopover();pageData.pins.push({id:`p-${Date.now()}`,x:pendingPin.x,y:pendingPin.y,text,time:nowTime()});hidePinPopover();renderPins();await saveAnnotation()}\nE.pinSave.onclick=commitPin;E.pinCancel.onclick=hidePinPopover;E.pinPopover.addEventListener('pointerdown',e=>e.stopPropagation());",'pin',re.S)
s=s.replace('addPinAt(e.clientX,e.clientY)','showPinPopover(e.clientX,e.clientY)').replace('addPinAt(touchState.startX,touchState.startY)','showPinPopover(touchState.startX,touchState.startY)')
s=s.replace('await saveNote();await saveAnnotation();currentPage','await Promise.all([saveNote(),saveTranscript(),saveAnnotation()]);currentPage',1)
s=s.replace("E.title.addEventListener('input',scheduleSave);","E.transcript.addEventListener('input',()=>{E.transcriptChars.textContent=`${E.transcript.value.length}자`;scheduleSave()});E.title.addEventListener('input',scheduleSave);",1)
s=s.replace("E.time.onclick=()=>insertText(`[${nowTime()}] `);","E.time.onclick=()=>insertText(`[${nowTime()}] `);E.viewCount.value=String(viewCount);E.viewCount.onchange=()=>{viewCount=Math.max(1,Math.min(4,Number(E.viewCount.value)||1));localStorage.setItem('lh-v4-view-count',String(viewCount));fit=true;if(pdfDoc)renderPage()};",1)
s=s.replace("function setupMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){E.mic.disabled=true;E.mic.title='이 브라우저는 음성입력을 지원하지 않습니다';return}recognition=new SR();recognition.lang='ko-KR';recognition.continuous=true;recognition.interimResults=false;recognition.onresult=e=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)t+=e.results[i][0].transcript+' ';if(t)insertText(t)};recognition.onend=()=>{listening=false;E.mic.textContent='🎤'};E.mic.onclick=()=>{if(listening){recognition.stop();return}try{recognition.start();listening=true;E.mic.textContent='⏹'}catch{}}}","function setupMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){E.mic.disabled=true;return}recognition=new SR();recognition.lang='ko-KR';recognition.continuous=true;recognition.interimResults=false;recognition.onresult=e=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)t+=e.results[i][0].transcript+' ';if(t.trim()){const q=E.transcript.value&&!E.transcript.value.endsWith('\\n')?'\\n':'';E.transcript.value+=`${q}[${nowTime()}] ${t.trim()}\\n`;E.transcript.dispatchEvent(new Event('input'))}};recognition.onend=()=>{listening=false;E.mic.textContent='🎤 시작';E.mic.classList.remove('listening')};E.mic.onclick=()=>{if(listening){recognition.stop();return}try{recognition.start();listening=true;E.mic.textContent='⏹ 중지';E.mic.classList.add('listening')}catch{}}}",1)
p.write_text(s)
print('patch A ok')
