from pathlib import Path
import re

def one(s,p,r,n,flags=0):
    x,c=re.subn(p,r,s,1,flags=flags)
    if c!=1: raise SystemExit(f'{n}:{c}')
    return x

p=Path('v4/styles.css');c=p.read_text()
if 'sheet4{' not in c:c+='''\n@media print{@page{size:A4 portrait;margin:8mm}#printArea{width:100%!important}.sheet4{width:100%;height:279mm;display:grid!important;grid-template-columns:1fr 1fr;grid-template-rows:1fr 1fr;gap:4mm;break-after:page;page-break-after:always}.sheet4:last-child{break-after:auto;page-break-after:auto}.slot4{min-width:0;min-height:0;border:1px solid #ddd;padding:2.5mm;display:flex;flex-direction:column;align-items:center;justify-content:flex-start;overflow:hidden;background:#fff}.slot4 .slotlabel{width:100%;font-size:9pt;font-weight:700;margin:0 0 1.5mm}.slot4 img{display:block;width:100%;height:calc(100% - 8mm);object-fit:contain}.slot4.empty4{border-color:transparent}}\n'''
p.write_text(c)

p=Path('v4/app.js');s=p.read_text()
s=s.replace("import {Document,Packer,Paragraph,TextRun,HeadingLevel,ImageRun,PageBreak,AlignmentType} from 'https://cdn.jsdelivr.net/npm/docx@9.8.1/+esm';","import {Document,Packer,Paragraph,TextRun,HeadingLevel,ImageRun,PageBreak,AlignmentType,Table,TableRow,TableCell,WidthType,PageOrientation} from 'https://cdn.jsdelivr.net/npm/docx@9.8.1/+esm';",1)
old="async function composePageImage(pageNo,renderScale=1.7){const page=await pdfDoc.getPage(pageNo),vp=page.getViewport({scale:renderScale});const c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);const ctx=c.getContext('2d');await page.render({canvasContext:ctx,viewport:vp}).promise;const a=await get(AS,`${project.id}:${pageNo}`);for(const s of a?.strokes||[]){const fake={...s,points:s.points.map(p=>({x:p.x*c.width,y:p.y*c.height,p:p.p}))};drawStrokeToContext(ctx,fake,renderScale)}return c}"
new="async function composePageImage(pageNo,renderScale=1.7){const page=await pdfDoc.getPage(pageNo),vp=page.getViewport({scale:renderScale});const c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);const ctx=c.getContext('2d');await page.render({canvasContext:ctx,viewport:vp}).promise;const a=await get(AS,`${project.id}:${pageNo}`);for(const s of a?.strokes||[]){const fake={...s,points:s.points.map(p=>({x:p.x*c.width,y:p.y*c.height,p:p.p}))};drawStrokeToContext(ctx,fake,renderScale)}for(const q of a?.pins||[]){ctx.save();ctx.fillStyle='#f59e0b';ctx.beginPath();ctx.arc(q.x*c.width,q.y*c.height,8*renderScale,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111827';ctx.font=`bold ${8*renderScale}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('!',q.x*c.width,q.y*c.height);ctx.restore()}return c}"
if old not in s: raise SystemExit('compose')
s=s.replace(old,new,1)
s=one(s,r"E\.md\.onclick=async\(\)=>\{.*?\};","E.md.onclick=async()=>{if(!project)return;await Promise.all([saveNote(),saveTranscript()]);const notes=await getByProject(NS,project.id),trans=await getByProject(TS,project.id);let out=`# ${E.title.value||project.title}\\n\\n`;for(let p=1;p<=pdfDoc.numPages;p++){const n=notes.find(x=>x.page===p),t=trans.find(x=>x.page===p);out+=`<<<PAGE ${p}>>>\\n\\n${p}p.\\n\\n### 코멘트\\n${n?.text||''}\\n\\n### 실시간 전사\\n${t?.text||''}\\n\\n`}downloadBlob(new Blob([out],{type:'text/markdown;charset=utf-8'}),`${safe(E.title.value)}_notes.md`)};",'md',re.S)
s=one(s,r"E\.json\.onclick=async\(\)=>\{.*?\};","E.json.onclick=async()=>{if(!project)return;await Promise.all([saveProject(),saveNote(),saveTranscript(),saveAnnotation()]);const notes=await getByProject(NS,project.id),transcripts=await getByProject(TS,project.id),annotations=await getByProject(AS,project.id);const payload={version:4,exportedAt:new Date().toISOString(),project:{...project,pdfBlob:undefined},notes,transcripts,annotations};downloadBlob(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),`${safe(E.title.value)}_backup.json`)};",'json',re.S)
s=s.replace("for(const n of j.notes||[])await put(NS,n);for(const a of j.annotations||[])await put(AS,a);","for(const n of j.notes||[])await put(NS,n);for(const t of j.transcripts||[])await put(TS,t);for(const a of j.annotations||[])await put(AS,a);",1)
s=one(s,r"E\.docx\.onclick=async\(\)=>\{.*?toast\('Word 완료'\)\};",'''async function fourUpCell(pageNo){if(pageNo>pdfDoc.numPages)return new TableCell({width:{size:50,type:WidthType.PERCENTAGE},children:[new Paragraph({text:''})]});const c=await composePageImage(pageNo,1.15),png=dataUrlToUint8(c.toDataURL('image/png'));const maxW=245,maxH=315,ratio=c.width/c.height;let w=maxW,h=w/ratio;if(h>maxH){h=maxH;w=h*ratio}return new TableCell({width:{size:50,type:WidthType.PERCENTAGE},children:[new Paragraph({children:[new TextRun({text:`${pageNo}p.`,bold:true,size:18})]}),new Paragraph({alignment:AlignmentType.CENTER,children:[new ImageRun({data:png,transformation:{width:Math.round(w),height:Math.round(h)}})]})]})}\nE.docx.onclick=async()=>{if(!project||!pdfDoc)return;toast('Word 4쪽 배치 생성 중…');await Promise.all([saveNote(),saveTranscript(),saveAnnotation()]);const children=[new Paragraph({text:E.title.value||project.title,heading:HeadingLevel.TITLE,alignment:AlignmentType.CENTER})];for(let start=1;start<=pdfDoc.numPages;start+=4){const cells=await Promise.all([0,1,2,3].map(i=>fourUpCell(start+i)));children.push(new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:[cells[0],cells[1]]}),new TableRow({children:[cells[2],cells[3]]})]}));if(start+4<=pdfDoc.numPages)children.push(new Paragraph({children:[new PageBreak()]}))}const doc=new Document({sections:[{properties:{page:{size:{width:11906,height:16838,orientation:PageOrientation.PORTRAIT},margin:{top:360,right:360,bottom:360,left:360}}},children}]});downloadBlob(await Packer.toBlob(doc),`${safe(E.title.value)}_4up.docx`);toast('Word 4쪽 배치 완료')};''','docx',re.S)
s=one(s,r"E\.printBtn\.onclick=async\(\)=>\{.*?setTimeout\(\(\)=>window\.print\(\),150\)\};",'''E.printBtn.onclick=async()=>{if(!project||!pdfDoc)return;toast('PDF 4쪽 배치 준비 중…');await Promise.all([saveNote(),saveTranscript(),saveAnnotation()]);E.printArea.innerHTML='';for(let start=1;start<=pdfDoc.numPages;start+=4){const sheet=document.createElement('article');sheet.className='sheet4';for(let i=0;i<4;i++){const p=start+i,slot=document.createElement('div');slot.className='slot4';if(p<=pdfDoc.numPages){const c=await composePageImage(p,1.05);slot.innerHTML=`<div class="slotlabel">${p}p.</div><img src="${c.toDataURL('image/jpeg',.9)}">`}else slot.classList.add('empty4');sheet.appendChild(slot)}E.printArea.appendChild(sheet)}setTimeout(()=>window.print(),180)};''','pdf',re.S)
p.write_text(s)
print('patch B ok')
